dist: trusty
sudo: required
language: go

go:
  - 1.15.x
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

env:
  global:
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "I/5PNi3hEv5FFDH3uL0S1SrVRzkDhtpOsfg23QvlZ0btAcOEEOgjp5mVov+5wORvbugtvpy+wMne0kxKtT1HXBewBGapDa7mfR5OH9keyo+aFDf/SLtW2RftxDavi2LhlakVpKBt4AseWCqrOTabhr/FkRQi2yBffbKYUKdu5po/zEouOcWVcQnxZdNvP1tcDQDfe74pqWCIq9L8wW0j7XNbWLZ9XxfdTysK4xSMfDCqwB2rwwVhHsB5ckz9ed77y2NUOg/OzQ1lIYKH90JV8WIkfxcmWGHliALZJHvOW4E6U6/Yf91ab1ZKbCBBREuN9cbS17WxlKsdgHOYr5P5GKIHf8chrNkPk0XfMZWvpVAVTkMruldjZZ+DKCV0//ShUx3lLeccDtM53akO//cMTZp+FQdKi+javJ31mAbO+hcNA1GnaqjxGRhYGJ1YcP6PrNgW/3062CKg5ZZQGOU6vpfAisegNh8p6h5lylTxPeOlaoyqPesTy1ySb7SQz095h+x3eVEQtthWI6OO3zePhDForHGc1USUdx4SJ1wlGXb/MlY+J35Uhb6OVJaqu7FIJABv+sToiUr3PQKOAgHKJ5e5VWDmApSH95PE0guZH16ijrmUBKeAOWKxh2afPnt4noOJqC7tP5xm8Mb+3XrLiVVz+pInYWRJQU/yK3DmbIk="

  matrix:
    - MYSQL_IMAGE=mysql/mysql-server:5.5
    - MYSQL_IMAGE=mysql/mysql-server:5.6
    - MYSQL_IMAGE=mysql/mysql-server:5.7
    - MYSQL_IMAGE=mysql/mysql-server:8.0
    - MYSQL_IMAGE=mariadb:5.5
    - MYSQL_IMAGE=mariadb:10.0
    - MYSQL_IMAGE=mariadb:10.1
    - MYSQL_IMAGE=mariadb:10.2
    - MYSQL_IMAGE=mariadb:10.3
    - MYSQL_IMAGE=percona/percona-server:5.6
    - MYSQL_IMAGE=percona/percona-server:5.7
    - MYSQL_IMAGE=percona/percona-server:8.0
    - MYSQL_IMAGE=percona:5.5
    - MYSQL_IMAGE=percona:5.6
    - MYSQL_IMAGE=percona:5.7
    - MYSQL_IMAGE=percona:8.0

services:
- docker

go_import_path: github.com/percona/mysqld_exporter

install:
  # install reviewdog and golangci-lin
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

before_script:
  # static analyze
  - bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
  - bin/golangci-lint run -c=.golangci.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review
  - sudo service mysql stop
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
- make
- make test

notifications:
  email: false
